services:

  credis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/data:/bitnami/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
  
  envoy:
    build: 
      context: envoy
    ports:
      - 8080:8080

  dispatcher:
    build: ./dispatcher
    depends_on:
      - redis
      - envoy
  
  gameserver:
    build: ./gameserver
    depends_on:
      - dispatcher
    ports:
      - 5000-5100:5000-5100
    
  

  

